version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://username:password@db:3006/dbname"
    volumes:
      - .:/app
      - /app/node_modules/bcrypt/

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "AlexLinov"
      POSTGRES_DB: PoolingObjects
